library(tidyverse)
library(svglite)
library(magrittr)
library(gganimate)
library(gifski)
library(rvest)

url1<-"https://docs.google.com/spreadsheets/d/1IZWQGzd3jQYOONuIi8eKBonA4lZ0xG1J4azf3dn81zk/pubhtml/sheet?headers=false&gid=0"

yt<- url1 %>% html_table()



yt<-read_csv("yachtski.csv")
yt %<>% group_by(Artist,Show.Number) %>% mutate(Cumsum=cumsum(YACHTSKI)) %>% mutate(value=cummean(YACHTSKI)) %>% ungroup()# %>% 
           #   group_by(Artist,Show.Number)




############################# RETRY ##############################################
gs<-list()
for ( i in  unique(yt$Show.Number)){
gs[[i]]<-yt[yt$Show.Number<=i,]
gs[[i]]$cumshow<-i  
  
}


gs<-bind_rows(gs) %>% group_by(cumshow,Artist) %>% summarize_at("value",max,na.rm=T) %>% ungroup()

anim_table <- gs %>%
  dplyr::group_by(cumshow) %>%
  dplyr::mutate(
    rank = row_number(-value) * 1,
    Value_rel = value/value[rank == 1],
    Value_lbl = paste0(" ", round(value,digits=0))
  ) %>% group_by(Artist) %>%
  dplyr::filter(rank <= 20)  %>%
  dplyr::ungroup()

###Break ties with this code: 

#anim_table<- anim_table %>% group_by(Artist) %>%
#  arrange(cumshow) %>%
#  mutate(prev.rank = lag(rank)) %>%
#  ungroup() %>% 
  
#  group_by(cumshow, rank) %>%
#  mutate(n = n_distinct(Artist)) %>%
#  mutate(width = 0.9 / n_distinct(Artist)) %>%
#  arrange(prev.rank) %>%
#  mutate(x = rank + 0.9 * (seq(1, 2 * n() - 1, by = 2) / 2 / n() - 0.5)) %>% mutate(x=ifelse(x>9,10))
#  ungroup() 


staticplot = ggplot(anim_table, aes(rank, group = Artist,fill=value)) + 
                geom_tile(aes(y = value/2,
                height = value,
                width = 0.9,fill=value), alpha = 0.8 ) +
  scale_fill_gradientn(colours = rev(terrain.colors(10))) + 
  geom_text(aes(y = 0, label = paste(Artist, " ")), vjust = 0.2, hjust = 1,size=(16*(5/14)),fontface = "bold") +
  geom_text(aes(y=value,label = Value_lbl, hjust=0),size=(14*(5/14))) +
  coord_flip(clip = "off", expand = FALSE) +
  scale_y_continuous(labels = scales::comma) +
  scale_x_reverse() +
  guides(color = FALSE, fill = FALSE) +
  theme(axis.line=element_blank(),
        axis.text.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks=element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(),
        legend.position="none",
        panel.background=element_blank(),
        panel.border=element_blank(),
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        panel.grid.major.x = element_line( size=.1, color="grey" ),
        panel.grid.minor.x = element_line( size=.1, color="grey"),
        plot.title=element_text(size=25, hjust=0.5, face="bold", colour="black", vjust=-1),
        plot.subtitle=element_text(size=18, hjust=0.5, face="italic", color="black"),
        plot.caption =element_text(size=14, hjust=0.5, face="italic", color="black",fontface="bold"),
        plot.background=element_blank(),
        plot.margin = margin(2,2, 2, 10, "cm"))


anim = staticplot + transition_states(cumshow, transition_length = 4, state_length = 1) +
  labs(title =   "The YACHTSKI-est* Yacht Rock Artists",
       subtitle  ='Beyond Yacht Rock Podcast Show Number : {closest_state}',
       caption  = "Cumulative Mean Yachtski Score | *of works scored at www.yachtrock.com/ | Plot generated by @jordan_wente") + 
         enter_fade() +  exit_fade()
 
      
  
animate(anim, 2000, fps = 15,  width = 1000, height = 800, 
        renderer = gifski_renderer("gganim.gif"))



################## now for NYachtski Score ##############################

anim_table_rev <- gs %>%
  dplyr::group_by(cumshow) %>%
  dplyr::mutate(
    rank = row_number(value) * 1,
    Value_rel = value/value[rank == 1],
    Value_lbl = paste0(" ", round(value,digits=0))
  ) %>% group_by(Artist) %>%
  dplyr::filter(rank <= 20)  %>%
  dplyr::ungroup()


staticplot = ggplot(anim_table_rev, aes(rank, group = Artist,fill=value)) + 
  geom_tile(aes(y = value/2,
                height = value,
                width = 0.9,fill=value), alpha = 0.8 ) +
  scale_fill_gradientn(colours = rev(terrain.colors(10))) + 
  geom_text(aes(y = 0, label = paste(Artist, " ")), vjust = 0.2, hjust = 1,size=(16*(5/14)),fontface = "bold") +
  geom_text(aes(y=value,label = Value_lbl, hjust=0),size=(14*(5/14))) +
  coord_flip(clip = "off", expand = FALSE) +
  scale_y_continuous(labels = scales::comma) +
  scale_x_reverse() +
  guides(color = FALSE, fill = FALSE) +
  theme(axis.line=element_blank(),
        axis.text.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks=element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(),
        legend.position="none",
        panel.background=element_blank(),
        panel.border=element_blank(),
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        panel.grid.major.x = element_line( size=.1, color="grey" ),
        panel.grid.minor.x = element_line( size=.1, color="grey"),
        plot.title=element_text(size=25, hjust=0.5, face="bold", colour="black", vjust=-1),
        plot.subtitle=element_text(size=18, hjust=0.5, color="black"),
        plot.caption =element_text(size=14, hjust=0.5, color="black"),
        plot.background=element_blank(),
        plot.margin = margin(2,2, 2, 10, "cm"))


anim = staticplot + transition_states(cumshow, transition_length = 4, state_length = 1) +
  labs(title =   "The NYACHTSKI-est* Yacht Rock Artists",
       subtitle  ='Beyond Yacht Rock Podcast Show Number : {closest_state}',
       caption  = "Cumulative Running Mean Yachtski Score (ranked by least Yacht) | *of works submitted and scored on the Podcast at www.yachtrock.com/ | Plot generated by @jordan_wente") + 
  enter_fade() +  exit_fade()



animate(anim, 2000, fps = 15,  width = 1000, height = 800, 
        renderer = gifski_renderer("gganim_rev.gif"))
